
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='grrmlog_parser',
    version='0.1.0',
    python_requires='==3.*,>=3.8.0',
    author='Your Name',
    author_email='you@example.com',
    packages=['grrmlog_parser', 'grrmlog_parser.models'],
    package_dir={"": "."},
    package_data={},
    install_requires=['numpy==1.*,>=1.19.4', 'pandas==1.*,>=1.1.3'],
    extras_require={"dev": ["pytest==5.*,>=5.2.0"]},
)
